/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "noIndex": false,
  "title": "JHipster 中文网",
  "favicon": "images/favicon.ico",
  "url": "https://www.jhipster.tech",
  "baseUrl": "/cn/",
  "deploymentBranch": "gh-pages",
  "organizationName": "jhipster",
  "projectName": "jhipster.github.io",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "onBrokenAnchors": "ignore",
  "i18n": {
    "defaultLocale": "zh-Hans",
    "locales": [
      "zh-Hans",
      "en",
      "jp"
    ],
    "localeConfigs": {
      "zh-Hans": {
        "label": "中文",
        "htmlLang": "zh-CN",
        "path": "https://www.jhipster.tech/cn",
        "direction": "ltr"
      },
      "en": {
        "label": "English",
        "htmlLang": "en-US",
        "path": "https://www.jhipster.tech",
        "direction": "ltr"
      },
      "jp": {
        "label": "日本語",
        "path": "https://www.jhipster.tech/jp",
        "direction": "ltr"
      }
    },
    "path": "i18n"
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/jhipster/jhipster.github.io/tree/main/",
          "routeBasePath": "/",
          "showLastUpdateTime": true,
          "versions": {
            "current": {
              "path": "/"
            }
          },
          "onlyIncludeVersions": [
            "current"
          ]
        },
        "blog": false,
        "theme": {
          "customCss": "./src/scss/custom.scss"
        },
        "sitemap": {
          "changefreq": "daily",
          "lastmod": "datetime",
          "ignorePatterns": [
            "/modules/marketplace/details/\\*",
            "/search"
          ]
        },
        "gtag": {
          "trackingID": "G-4L9RJVPGJT",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "plugins": [
    "docusaurus-plugin-sass",
    [
      "@docusaurus/plugin-client-redirects",
      {
        "redirects": [
          {
            "from": "/jdl/",
            "to": "/jdl/intro"
          },
          {
            "from": [
              "/cloudcaptain.html",
              "/boxfuse.html",
              "/boxfuse/"
            ],
            "to": "/cloudcaptain/"
          },
          {
            "from": "/configuring_a_corporate_proxy.html",
            "to": "/configuring-a-corporate-proxy/"
          },
          {
            "from": "/configuring_ide_eclipse.html",
            "to": "/configuring-ide-eclipse/"
          },
          {
            "from": "/configuring_ide_idea.html",
            "to": "/configuring-ide-idea/"
          },
          {
            "from": "/configuring_ide_netbeans.html",
            "to": "/configuring-ide-netbeans/"
          },
          {
            "from": "/configuring_ide.html",
            "to": "/configuring-ide/"
          },
          {
            "from": [
              "/thanks.html",
              "/thanks/"
            ],
            "to": "/contributing-companies/"
          },
          {
            "from": "/creating_an_app.html",
            "to": "/creating-an-app/"
          },
          {
            "from": "/creating_an_entity.html",
            "to": "/creating-an-entity/"
          },
          {
            "from": [
              "/customizing_bootstrap.html",
              "/customizing-bootstrap-3/",
              "/customizing-bootstrap-4/"
            ],
            "to": "/customizing-bootstrap/"
          },
          {
            "from": "/docker_compose.html",
            "to": "/docker-compose/"
          },
          {
            "from": "/docker_hub.html",
            "to": "/docker-hub/"
          },
          {
            "from": "/installing_new_languages.html",
            "to": "/installing-new-languages/"
          },
          {
            "from": "/jhipster_uml.html",
            "to": "/jhipster-uml/"
          },
          {
            "from": "/managing_relationships.html",
            "to": "/managing-relationships/"
          },
          {
            "from": "/running_tests.html",
            "to": "/running-tests/"
          },
          {
            "from": "/setting_up_ci_jenkins2.html",
            "to": "/setting-up-ci-jenkins2/"
          },
          {
            "from": "/setting_up_ci_linux.html",
            "to": "/setting-up-ci-linux/"
          },
          {
            "from": "/setting_up_ci_windows.html",
            "to": "/setting-up-ci-windows/"
          },
          {
            "from": "/setting_up_ci.html",
            "to": "/setting-up-ci/"
          },
          {
            "from": "/tech_stack.html",
            "to": "/tech-stack/"
          },
          {
            "from": "/using_angularjs.html",
            "to": "/using-angularjs/"
          },
          {
            "from": "/using_cassandra.html",
            "to": "/using-cassandra/"
          },
          {
            "from": "/using_couchbase.html",
            "to": "/using-couchbase/"
          },
          {
            "from": "/using_dtos.html",
            "to": "/using-dtos/"
          },
          {
            "from": "/using_elasticsearch.html",
            "to": "/using-elasticsearch/"
          },
          {
            "from": "/using_kafka.html",
            "to": "/using-kafka/"
          },
          {
            "from": "/using_mongodb.html",
            "to": "/using-mongodb/"
          },
          {
            "from": "/using_oracle.html",
            "to": "/using-oracle/"
          },
          {
            "from": "/using_pulsar.html",
            "to": "/using-pulsar/"
          },
          {
            "from": "/using_websockets.html",
            "to": "/using-websockets/"
          },
          {
            "from": "/using_neo4j.html",
            "to": "/using-neo4j/"
          },
          {
            "from": "/video_tutorial.html",
            "to": "/video-tutorial/"
          },
          {
            "from": [
              "/creating_a_blueprint.html",
              "/modules/creating_a_blueprint.html"
            ],
            "to": "/modules/creating-a-blueprint/"
          },
          {
            "from": [
              "/creating_a_module.html",
              "/modules/creating_a_module.html"
            ],
            "to": "/modules/creating-a-module/"
          },
          {
            "from": [
              "/extending_and_customizing.html",
              "/modules/extending_and_customizing.html"
            ],
            "to": "/modules/extending-and-customizing/"
          },
          {
            "from": [
              "/official-blueprints.html",
              "/modules/official-blueprints.html"
            ],
            "to": "/modules/official-blueprints/"
          },
          {
            "from": "/companies-using-jhipster/companies-using-jhipster.html",
            "to": "/companies-using-jhipster/"
          },
          {
            "from": "/2022/09/02/jhipster-release-7.9.4.html",
            "to": "/2023/09/05/jhipster-release-7.9.4.html"
          },
          {
            "from": "/2024/12/23/jhipster-release-8.9.0.html",
            "to": "/2025/02/08/jhipster-release-8.9.0.html"
          },
          {
            "from": "/blueprints/quarkus.html",
            "to": "/blueprints/quarkus/"
          },
          {
            "from": "/artwork.html",
            "to": "/artwork/"
          },
          {
            "from": "/modules/marketplace.html",
            "to": "/modules/marketplace/"
          },
          {
            "from": "/clever-cloud.html",
            "to": "/clever-cloud/"
          },
          {
            "from": "/configuring-ide-eclipse-gradle.html",
            "to": "/configuring-ide-eclipse-gradle/"
          },
          {
            "from": "/development.html",
            "to": "/development/"
          },
          {
            "from": "/doing-api-first-development.html",
            "to": "/doing-api-first-development/"
          },
          {
            "from": "/fisher.html",
            "to": "/fisher/"
          },
          {
            "from": "/fisherman.html",
            "to": "/fisherman/"
          },
          {
            "from": "/help.html",
            "to": "/help/"
          },
          {
            "from": "/heroku.html",
            "to": "/heroku/"
          },
          {
            "from": "/installation.html",
            "to": "/installation/"
          },
          {
            "from": "/kubernetes.html",
            "to": "/kubernetes/"
          },
          {
            "from": "/meetups.html",
            "to": "/meetups/"
          },
          {
            "from": "/oh-my-zsh.html",
            "to": "/oh-my-zsh/"
          },
          {
            "from": "/policies.html",
            "to": "/policies/"
          },
          {
            "from": "/production.html",
            "to": "/production/"
          },
          {
            "from": "/profiles.html",
            "to": "/profiles/"
          },
          {
            "from": "/releases.html",
            "to": "/releases/"
          },
          {
            "from": "/screenshots.html",
            "to": "/screenshots/"
          },
          {
            "from": "/security.html",
            "to": "/security/"
          },
          {
            "from": "/shell-plugins.html",
            "to": "/shell-plugins/"
          },
          {
            "from": "/showcase.html",
            "to": "/showcase/"
          },
          {
            "from": "/team.html",
            "to": "/team/"
          },
          {
            "from": "/tips.html",
            "to": "/tips/"
          }
        ]
      }
    ],
    "./src/plugins/google-fonts.ts",
    "./src/plugins/module-details.ts",
    "plugin-image-zoom"
  ],
  "themeConfig": {
    "metadata": [
      {
        "name": "author",
        "content": "JHipster Team"
      },
      {
        "name": "twitter:site",
        "content": "@jhipster"
      },
      {
        "name": "google-site-verification",
        "content": "JSA7VC5gSwD5KKbXlxK8F9rXJtC91rKJq0aWhfpBC0k"
      }
    ],
    "image": "images/twitter-card.png",
    "navbar": {
      "logo": {
        "alt": "JHipster Logo",
        "src": "images/logo/logo-light.svg",
        "srcDark": "images/logo/logo-dark.svg",
        "width": 140,
        "height": 32
      },
      "items": [
        {
          "to": "/getting-started",
          "label": "文档",
          "position": "right"
        },
        {
          "to": "/modules/marketplace/",
          "label": "应用市场",
          "position": "right"
        },
        {
          "to": "/team/",
          "label": "团队",
          "position": "right"
        },
        {
          "to": "/sponsors/",
          "label": "赞助商",
          "position": "right"
        },
        {
          "href": "https://start.jhipster.tech/jdl-studio/",
          "label": "JDL 工作室",
          "position": "right"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ],
      "hideOnScroll": false
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "java",
        "bash",
        "yaml",
        "gradle",
        "diff"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "algolia": {
      "appId": "T3OWTRXITU",
      "apiKey": "012c1b755b9e42f5e300959da6ad25cd",
      "indexName": "jhipster",
      "contextualSearch": false,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "imageZoom": {
      "selector": ".markdown :not(em) > img"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "headTags": [
    {
      "tagName": "script",
      "attributes": {
        "type": "application/ld+json"
      },
      "innerHTML": "{\"@context\":\"https://schema.org/\",\"@type\":\"Organization\",\"name\":\"JHipster\",\"url\":\"https://www.jhipster.tech\",\"logo\":\"https://www.jhipster.tech/images/logo/logo.svg\",\"sameAs\":[\"https://x.com/jhipster\",\"https://github.com/jhipster/generator-jhipster\"]}"
    }
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "tagline": "",
  "titleDelimiter": "|",
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
